name: WordPress Docker Setup with MySQL

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    # Install dependencies
      - name: Install dependencies
        run: npm install
        # step : run cypress
      - name: run cypress test
        run: |
          npm run e2e:chrome
         # Upload Cypress Mochawesome report as an artifact
      - name: Upload Cypress Mochawesome Report
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: |
            cypress/reports
            cypress/screenshots
            cypress/videos



   

      
          
     

     
